### ISSUE TITLE
Why remove fcos and add foveabox ？

### ISSUE THREAD

**Issue by ianz27** [chenjoya/sampling-free#1]

**Comment by chenjoya** [comment]
Hi, in our experiments, the FCOS (Sampling-Free) has lower 0.2~0.3 AP than FCOS (FocalLoss). We attribute this to the ``centerness`` branch, it affects the threshold moving during inference. The FoveaBox, however, is a simple and clean pipeline that has no ``centerness`` branch. It works well with Sampling-Free mechanism.
