### ISSUE TITLE
Where are the code about sampling-free?

### ISSUE THREAD

**Issue by zychen2016** [chenjoya/sampling-free#4]
## ❓ Questions and Help

Could you point out where are the code about your sampling-free function?
Because I am not familiar with maskrcnn_benchmark, Just want to use sampling-free function in other networks.

Thank you very much.

**Comment by chenjoya** [comment]
Hi @zychen2016, the core code of our method could be found in ```maskrcnn_benchmark/modeling/sampling-free.py```: https://github.com/ChenJoya/sampling-free/blob/master/maskrcnn_benchmark/modeling/sampling_free.py.
