### ISSUE TITLE
for two-stage detector, bias init only apply in rpn?

### ISSUE THREAD

**Issue by hust-kevin** [chenjoya/sampling-free#5]
## ❓ Questions and Help
for two-stage detector, bias init only apply in rpn while bbox head not need?

**Comment by chenjoya** [comment]
Yeah, it's a good question!

In fact, there is an extreme fg-bg imbalance in RPN, so the optimal bias initialization should be adopted.

However, we find that in RoI-stage, the imbalance has been greatly alleviated, and it is no problem to use only guided loss. This has been illustrated in our appendix.

Thank you for your attention to our work!

**Comment by hust-kevin** [comment]
one more question, in [sampling_free.py](https://github.com/ChenJoya/sampling-free/blob/master/maskrcnn_benchmark/modeling/sampling_free.py#L180),  to get the score_thr, we need know the prior, for two stage, how to compute prior in roi-stage, in AdaptiveInitializer only support one-stage and rpn?

**Comment by chenjoya** [comment]
Here we empirically set the threshold as 0.001 for roi-stage. 

The pos:neg ≈ 1:10 in that stage.

For softmax classifier the score_thr could be computed by prior / num_classes = 0.1 / 80 ≈ 0.001.

But there is no obvious difference for **the enough lower score_thr value** while computing AP.
