### ISSUE TITLE
The result of Pascal VOC seems bad.

### ISSUE THREAD

**Issue by SkeletonOne** [chenjoya/sampling-free#6]
## ❓ Questions and Help
Hi Joya,
Currently, I am training retinanet voc 0.2x as the method you provide in the README. Since the pascal voc data is in COCO format, the default evaluation method is the coco evaluation method. The results are:
`
Accumulating evaluation results...
DONE (t=6.31s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.457
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.722
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.482
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.125
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.321
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.540
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.582
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.600
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.255
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.510
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.671
2020-04-01 17:57:02,155 maskrcnn_benchmark.inference INFO: 
Task: bbox
AP, AP50, AP75, APs, APm, APl
0.4572, 0.7220, 0.4823, 0.1246, 0.3206, 0.5403
`
Since the voc result is AP50 in COCO evaluation style, it is only 0.722 here. I am wondering how to get the result you provide. Or in other words, am I possible to use pascal voc evaluation tool in this project or the maskrcnn-benchmark? Maybe that will provide the 79+result. I'm not sure, but how to get the result in your README?
Thanks!

**Comment by chenjoya** [comment]
Thanks for your attention. That's interesting. It seems that your configuration is incorrect, as training on voc dataset would not call COCO-style evaluation procedure. We have provide "retinanet_voc_R_50_FPN_0.2x.yaml" in configs (configs/retinanet/retinanet_voc_R_50_FPN_0.2x.yaml). Just try it!

**Comment by SkeletonOne** [comment]
@ChenJoya I used your configs (.yaml) in detectron2 and the annotations were COCO format so the result was like this.... After training pascal voc in its own style I got AP50 about 78.6. Everything seems normal now. Thanks for your work again.

**Comment by chenjoya** [comment]
Sorry， but it should be 80+ mAP？


------------------ Original ------------------

**Comment by SkeletonOne** [comment]
Sorry about my unclarity. I was just implementing the original retinanet, without sampling free : )

Since the retinanet paper did not train on Pascal VOC, I was just trying to get the AP of base Retinanet first. Thanks for your kindly reply!

**Comment by chenjoya** [comment]
Yeah, the vanilla RetinaNet does not seem to do&nbsp;well on PASCAL VOC. Good&nbsp;luck!


------------------ Original ------------------
